#!/usr/bin/env python3
"""Generate rp_ddr_1gb_patch.c by diffing two generated ps7_init.c files.

The 512 MB and 1 GB Red Pitaya boards differ only in the DDR bus width
(PCW_UIPARAM_DDR_BUS_WIDTH / DRAM_WIDTH), so the two FSBL builds differ only in
the values of a handful of DDRC and DDRIOB registers. This script extracts that
delta so a single FSBL can carry the 512 MB tables and patch them in place when
the board turns out to be a 1 GB one.

Patches are recorded as word offsets into the generated arrays, not as
addresses: ddrc_ctrl (0xF8006000) is written twice with different values, so an
address alone is not unique. The offset is emitted together with the opcode and
address found there, which the patcher re-checks before writing.

Every assumption the patcher relies on is verified here and any violation is
fatal, so an upstream change can never silently produce a wrong FSBL.
"""

import argparse
import re
import sys
from pathlib import Path

# EMIT_MASKWRITE(0XF8006000, 0x0001FFFFU ,0x00000080U),
EMIT = re.compile(r"\bEMIT_(\w+)\s*\(([^)]*)\)")

# unsigned long ps7_ddr_init_data_3_0[] = {
ARRAY = re.compile(r"\b(?:static\s+)?unsigned\s+long\s+"
                   r"(ps7_\w+_init_data_\w+|ps7_post_config_\w+)\s*\[\s*\]\s*=\s*\{")

# Number of arguments each opcode carries; the array stores opcode + args.
OPCODE_ARGS = {"EXIT": 0, "CLEAR": 1, "WRITE": 2,
               "MASKWRITE": 3, "MASKPOLL": 2, "MASKDELAY": 2}
OPCODE_NUM = {"EXIT": 0, "CLEAR": 1, "WRITE": 2,
              "MASKWRITE": 3, "MASKPOLL": 4, "MASKDELAY": 5}

# Register windows a difference is allowed to fall into. Xilinx spreads the
# DDRIOB writes across the mio, ddr and peripherals tables, so the window
# matters more than which table an entry lives in.
ALLOWED_WINDOWS = (
    (0xF8006000, 0xF8006FFF, "DDRC"),
    (0xF8000B00, 0xF8000BFF, "DDRIOB"),
)


def fail(msg):
    sys.exit(f"gen_ddr_patch: {msg}")


def parse_num(tok):
    tok = tok.strip().rstrip("Uu")
    return int(tok, 0) if tok else None


def extract_arrays(path):
    """Return {array name: [(kind, args, word_offset), ...]}."""
    text = path.read_text(errors="replace")
    arrays = {}

    for m in ARRAY.finditer(text):
        name = m.group(1)
        depth, i = 1, m.end()
        while i < len(text) and depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        if depth:
            fail(f"{path.name}: unterminated initializer for '{name}'")

        entries, offset = [], 0
        for kind, raw in EMIT.findall(text[m.end():i - 1]):
            if kind not in OPCODE_ARGS:
                fail(f"{path.name}: unknown opcode EMIT_{kind} in '{name}'")
            args = tuple(parse_num(a) for a in raw.split(",")) if raw.strip() else ()
            if len(args) != OPCODE_ARGS[kind]:
                fail(f"{path.name}: EMIT_{kind} in '{name}' has {len(args)} args")
            entries.append((kind, args, offset))
            offset += 1 + OPCODE_ARGS[kind]
        arrays[name] = entries

    if not arrays:
        fail(f"{path.name}: no ps7_* tables found")
    return arrays


def window_of(addr):
    for lo, hi, label in ALLOWED_WINDOWS:
        if lo <= addr <= hi:
            return label
    return None


def diff_table(ea, eb, name):
    """Return [(word_offset, addr, mask, value)] the 1 GB build needs."""
    if len(ea) != len(eb):
        fail(f"'{name}': entry count differs ({len(ea)} vs {len(eb)}). "
             f"In-place patching cannot add or remove entries.")

    patch = []
    for idx, ((ka, aa, oa), (kb, ab, ob)) in enumerate(zip(ea, eb)):
        if ka != kb or oa != ob:
            fail(f"'{name}' entry {idx}: layout differs ({ka}@{oa} vs {kb}@{ob})")
        if ka == "EXIT" or aa == ab:
            continue
        if aa[0] != ab[0]:
            fail(f"'{name}' entry {idx}: address differs "
                 f"({aa[0]:#x} vs {ab[0]:#x})")

        addr = aa[0]
        if ka != "MASKWRITE":
            fail(f"'{name}' entry {idx}: differing {ka} at {addr:#x} - the init "
                 f"sequence changed, not just a register value")
        if window_of(addr) is None:
            fail(f"'{name}' entry {idx}: differing register {addr:#x} lies "
                 f"outside the DDRC/DDRIOB windows")
        patch.append((oa, addr, ab[1], ab[2]))
    return patch


def emit(patches, out_path):
    lines = [
        "/* Generated by gen_ddr_patch.py - do not edit.",
        " * Register values that turn the 512 MB (16-bit bus) DDR configuration",
        " * into the 1 GB (32-bit bus) one, extracted by diffing the two builds.",
        " */",
        '#include "rp_ddr_patch.h"',
        "",
    ]
    for name in sorted(patches):
        lines.append(f"extern unsigned long {name}[];")
    lines.append("")

    for name, patch in sorted(patches.items()):
        lines.append(f"static const rp_ddr_patch_entry_t patch_{name}[] = {{")
        for off, addr, mask, val in patch:
            lines.append(f"    {{ {off}u, 0x{addr:08X}u, "
                         f"0x{mask:08X}u, 0x{val:08X}u }},")
        lines.append("};")
        lines.append("")

    lines.append("const rp_ddr_patch_table_t rp_ddr_1gb_tables[] = {")
    for name, patch in sorted(patches.items()):
        lines.append(f"    {{ {name}, patch_{name}, {len(patch)}u }},")
    lines.append("};")
    lines += [
        "",
        "const unsigned rp_ddr_1gb_tables_len =",
        "    (unsigned)(sizeof(rp_ddr_1gb_tables) / sizeof(rp_ddr_1gb_tables[0]));",
        "",
    ]
    out_path.write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ps7-512", required=True, help="ps7_init.c from RAM=512")
    ap.add_argument("--ps7-1024", required=True, help="ps7_init.c from RAM=1024")
    ap.add_argument("--out", required=True, help="output rp_ddr_1gb_patch.c")
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    p512, p1024 = Path(args.ps7_512), Path(args.ps7_1024)
    for p in (p512, p1024):
        if not p.is_file():
            fail(f"{p} not found")

    a, b = extract_arrays(p512), extract_arrays(p1024)
    if sorted(a) != sorted(b):
        fail(f"the two builds expose different tables: "
             f"{sorted(set(a) ^ set(b))}")

    patches = {}
    for name in sorted(a):
        patch = diff_table(a[name], b[name], name)
        if patch:
            patches[name] = patch

    if not patches:
        fail("the two builds are identical - were they really built with "
             "different RAM settings?")

    emit(patches, Path(args.out))

    total = sum(len(p) for p in patches.values())
    print(f"gen_ddr_patch: {len(patches)} table(s) patched, "
          f"{total} register writes")
    if args.report:
        for name, patch in sorted(patches.items()):
            print(f"  {name}:")
            for off, addr, mask, val in patch:
                print(f"    +{off:<5} {addr:#010x}  mask {mask:#010x}  "
                      f"val {val:#010x}  [{window_of(addr)}]")


if __name__ == "__main__":
    main()
